# -*- coding: utf-8 -*-
"""Gerador de Roteiros para Vídeos do YouTube - Imersão IA Alura + Google Gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_CLlcfOhMOL5LOREqSFPFBXFrWRka1C
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-genai

# Configura a API Key do Google Gemini

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

# Configura o cliente da SDK do Gemini

from google import genai

client = genai.Client()

MODEL_ID = "gemini-2.0-flash"

# Instalar Framework ADK de agentes do Google ################################################
!pip install -q google-adk

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.genai import types  # Para criar conteúdos (Content e Part)
from datetime import date
import textwrap # Para formatar melhor a saída de texto
from IPython.display import display, Markdown # Para exibir texto formatado no Colab
import requests # Para fazer requisições HTTP
import warnings

warnings.filterwarnings("ignore")

# Função auxiliar que envia uma mensagem para um agente via Runner e retorna a resposta final
def call_agent(agent: Agent, message_text: str) -> str:
    # Cria um serviço de sessão em memória
    session_service = InMemorySessionService()
    # Cria uma nova sessão (você pode personalizar os IDs conforme necessário)
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    # Cria um Runner para o agente
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    # Cria o conteúdo da mensagem de entrada
    content = types.Content(role="user", parts=[types.Part(text=message_text)])

    final_response = ""
    # Itera assincronamente pelos eventos retornados durante a execução do agente
    for event in runner.run(user_id="user1", session_id="session1", new_message=content):
        if event.is_final_response():
          for part in event.content.parts:
            if part.text is not None:
              final_response += part.text
              final_response += "\n"
    return final_response

# Função auxiliar para exibir texto formatado em Markdown no Colab
def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

##########################################
# --- Agente 1: Buscador de Notícias --- #
##########################################
def agente_buscador(topico, data_de_hoje):
    buscador = Agent(
        name="agente_buscador",
        model="gemini-2.0-flash",
        description="Agente que busca informações no Google",
        tools=[google_search],
        instruction="""
        Você é um assistente de pesquisa. Seu objetivo é usar a ferramenta do Google (google_search) para buscar
        as notícias mais atuais sobre conteúdos de grande impacto no tópico especificado.
        Priorize um máximo de 5 conteúdos, cuja relevância será medida pela quantidade de notícias e
        pelo entusiasmo que despertam. Se um item específico gerar poucas notícias ou não demonstrar um forte
        interesse público/midiático, ele provavelmente não é relevante o suficiente e deve ser trocado por um
        que tenha maior destaque. O conteúdo pesquisado deve obrigatóriamente respeitar as Políticas e diretrizes da comunidade do YouTube,
        caso contrário um aviso deverá ser emitido. É fundamental que os conteúdos sejam recentes, ocorridos dentro
        do último mês a contar da data de hoje.
        """
    )
    entrada_do_agente_buscador = f"Tópico: {topico}\nData de hoje: {data_de_hoje}"
    conteudos= call_agent(buscador, entrada_do_agente_buscador)
    return conteudos

#########################################################
# --- Agente 2: Planejador de roteiros para YouTube --- #
#########################################################
def agente_planejador(topico, conteudos_buscados):
    planejador = Agent(
        name="agente_planejador",
        model="gemini-2.0-flash",
        description="Agente que planeja roteiros para vídeos do YouTube",
        tools=[google_search],
        # Inserir as instruções do Agente Planejador #################################################
        instruction="""
        Assumindo o papel de planejador de conteúdo com expertise em YouTube, minha tarefa é,
        a partir de uma lista fornecida de conteúdos relevantes que foram pesquisados, usar a ferramenta do
        Google (google_search). Para cada item da lista, pesquisarei para determinar os pontos cruciais a serem
        cobertos em um roteiro e buscarei informações adicionais para aprofundamento.
        Após essa análise, selecionarei o tema de maior relevância encontrado através das pesquisas e retornarei:
        o tema selecionado, seus pontos-chave e uma estrutura de roteiro contendo os assuntos a serem abordados.
        """
    )

    entrada_do_agente_planejador = f"Tópico:{topico}\nConteúdos buscados: {conteudos_buscados}"
    # Executa o agente
    plano_do_post = call_agent(planejador, entrada_do_agente_planejador)
    return plano_do_post

######################################################
# --- Agente 3: Redator de roteiros para YouTube --- #
######################################################
def agente_redator(topico, plano_de_post):
    redator = Agent(
        name="agente_redator",
        model="gemini-2.5-flash-preview-04-17",
        description="Agente redator de roteiros para vídeos do YouTube",
        instruction="""
        Assumindo a persona de um Redator Criativo Especialista em roteiros para YouTube, meu objetivo é transformar o tema
        e os pontos-chave de um plano de conteúdo em um rascunho de roteiro de vídeo. O roteiro final deverá ser
        envolvente, educativo, de fácil compreensão, estruturado em tópicos e com duração mínima de 10 minutos.
        Complementando o roteiro, fornecerei opções de títulos e conceitos de thumbnails (capas) que sejam ambos
        impactantes e SEO-friendly, bem como uma descrição de vídeo com foco em SEO.
            """
    )
    entrada_do_agente_redator = f"Tópico: {topico}\nPlano de post: {plano_de_post}"
    # Executa o agente
    rascunho = call_agent(redator, entrada_do_agente_redator)
    return rascunho

##########################################
# --- Agente 4: Revisor de Qualidade --- #
##########################################
def agente_revisor(topico, rascunho_gerado):
    revisor = Agent(
        name="agente_revisor",
        model="gemini-2.5-flash-preview-04-17",
        description="Agente revisor de roteiros para vídeos do YouTube.",
        instruction="""
            Você atuará como um Editor e Revisor especializado em roteiros para YouTube, com a responsabilidade
            de refinar conteúdos para o público que tenha interesse no tópico pesquisado, mantendo um tom apropriado.
            Receberá um rascunho de roteiro para revisar, verificando a clareza da mensagem, a concisão, a
            correção (gramatical, factual, etc.) e a aderência ao tom desejado. Após a avaliação: se o rascunho estiver excelente,
            responda somente com '👍 Show de bola! O roteiro ficou ótimo e está pronto para ser usado.'. Caso contrário,
            detalhe os problemas identificados e proponha as melhorias necessárias.
            """
    )
    entrada_do_agente_revisor = f"Tópico: {topico}\nRascunho: {rascunho_gerado}"
    # Executa o agente
    texto_revisado = call_agent(revisor, entrada_do_agente_revisor)
    return texto_revisado

data_de_hoje = date.today().strftime("%d/%m/%Y")

print("🚀 Iniciando o Gerador de Roteiros para vídeos do YouTube 🚀")

# --- Obter o Tópico do Usuário ---
tema = input("\n ▶️ Por favor, digite o tema do seu vídeo para o YouTube: ")

# Inserir lógica do sistema de agentes ################################################
if not tema:
  print("\n ⚠️ Opa, foi mal, mas você esqueceu de digitar o tema do seu vídeo!🤷‍♂️")
else:
  print(f"\n 🎬 Ok, hora de gerar um ROTEIRO sobre {tema}. \n\n ⌛ Processando, aguarde um instante...")

  conteudos_buscados = agente_buscador(tema, data_de_hoje)
  print("\n ⌛ Aguarde mais um pouquinho... \n")
  # display(to_markdown(conteudos_buscados))
  # print("-----------------------------------------------------------")

  plano_de_post = agente_planejador(tema, conteudos_buscados)
  print("😊 Já estou finalizando, tenha paciência! \n")
  # display(to_markdown(plano_de_post))
  print("-----------------------------------------------------------")

  rascunho_de_post = agente_redator(tema, plano_de_post)
  print("\n --- AQUI ESTÁ O SEU ROTEIRO ---\n")
  display(to_markdown(rascunho_de_post))
  print("-----------------------------------------------------------")

  post_final = agente_revisor(tema, rascunho_de_post)
  print("\n --- Revisão do ROTEIRO ---\n")
  display(to_markdown(post_final))
  print("-----------------------------------------------------------")